name: ${project.name}
main: com.poixson.discord.DiscordPlugin
version: '${project.version}'
api-version: '${bukkit-short-version}'
dependencies:
    server:
        VitalCore:
            load: BEFORE
            required: true
authors: lorenzop
website: ${project.url}
description: ${project.description}
permissions:
    discord.*:
        default: op
        description: Allow all discord commands
        children:
            discord.cmd.link:   true
            discord.cmd.unlink: true
    discord.cmd.link:
        default: op
        description: "Allow command: /link"
    discord.cmd.unlink:
        default: op
        description: "Allow command: /unlink"
